version: "2"
services:
  pypi_web:
    build: .
    container_name: pypi_web
    hostname: pypi_web
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    networks:
      - default
      - nginx

networks:
  nginx:
    external:
      name: nginx_nginx
